### ISSUE TITLE
Use SIL Open Font License instead of GPL3.0

### ISSUE THREAD

**Issue by dspreadbury** [MarcSabatella/Campania#1]
I think it would be excellent if you would consider releasing Campania under the SIL Open Font License rather than the GPL, since the OFL is friendlier to a wider range of options for distribution and derivation. Thanks for considering it.

**Comment by MarcSabatella** [comment]
Thanks for the feedback!  I do agree this makes sense.  Unfortunately, it's currently based on FreeSerif, which is GPL, and I'm not sure there is a way out of that.  On the other hand, the way I have things set up, it's not that much work to change to a different base font.  That's something I've been discussing with a few others offline.  Let me know if there are any particular candidates you'd recommend.

**Comment by MarcSabatella** [comment]
BTW, I know we also discussed the possibility of standardizing something like this as part of SMuFL.  I'm still quite interested in that, although I'm not really sure what that would look like.  I gather BravuraText doesn't include standard alphanumeric characters, and am assuming that was a conscious design, but it sure would seem to make sense for any font to be used for RNA to include the ASCII range.

**Comment by dspreadbury** [comment]
A good alternative font that is licensed under the OFL is [SIL Doulos](https://software.sil.org/doulos/).

There's certainly an argument for encoding the symbols used in Roman numeral analysis in SMuFL. We haven't done so until now because there are (to my knowledge) no symbols used in Roman numeral analysis that are not already encoded, and certainly we do not want to encode the standard alphanumeric characters away from their Basic Latin codepage locations, so we've always concluded that there is limited utility in doing this, but it's always up for debate, of course.

**Comment by MarcSabatella** [comment]
The way my font is designed, the combinations like 64 etc are ligatures with their own codepoints.  And the superscripted individual numerals are as well, although I'm in the processing of changing that.  So those are the ones I think could be useful to encode in SMuFL.  It's also possible, of course, to define the font to not use ligatures, but instead of OpenType positioning, but that gets to be rather complex, at least for me.

**Comment by MarcSabatella** [comment]
Update:

I have now released version 2 of Campania, based on Doulos and licensed under SIL OFL terms (and if I got anything wrong in how I set that up, let me know what I would need to do to correct it).

This version no longer uses ligatures for things like the numeral stacks 64, 653, etc.  Instead it uses OpenType positioning rules.  This has several advantages.  One is, no new codepoints required for these.  Another is you can have whatever oddball stacks you want (V752, anyone?).  Another is that this makes it that much easier to plgu in a different base font but still use the same substitution and positioning rules.

The only new codepoints I use in this version of the font are superscripted accidentals, for compatibility with the standard Unicode superscript numerals.  Not sure if any of the SMuFL codepoints would work for this, but I use these to allow things like bV7b9 with everything after the V superscripted.

**Comment by dspreadbury** [comment]
This looks good to me, @MarcSabatella. The only issue I see is that you need to update LICENSE to be the SIL OFL. I'll raise a pull request.

**Comment by MarcSabatella** [comment]
Great, thanks!  I had updated the license text within the font metadata, but forgot the file in GitHub.
