### ISSUE TITLE
Augmentation '+' doesn't sub/superscript

### ISSUE THREAD

**Issue by billhails** [MarcSabatella/Campania#10]
Hi, me again, I just updated to MuseScore 3.3 and was delighted to see that they now have your font and RNA built in.
However I was surprised when typing i.e. III+ for three augmented that the + didn't become a superscript. Is this just an oversight or is there some reason you don't support this?

Many thanks again for this great addition to MuseScore.

**Comment by MarcSabatella** [comment]
Do you perhaps have an older version of Campania installled on your system?  Remove it so MuseScore can use its own bundled version, or update your installed version to the current - I added that support a couple of weeks ago.

**Comment by billhails** [comment]
Oh, of course, I was using Campania with MS before it was bundled, I'll remove the old one.

**Comment by billhails** [comment]
Works now, thanks!
