### ISSUE TITLE
Apply layouting to other existing fontfaces

### ISSUE THREAD

**Issue by ecstrema** [MarcSabatella/Campania#11]
Hi,
In the readme, you wrote that you used the glyphs from doulos.
Would it be possible to simply replace the glyphs with these of freeserif or musejazz to get the substitutions on different fonts?
Thks

**Comment by ecstrema** [comment]
Actually this is a stupid comment. I'll try it and tell you.

**Comment by MarcSabatella** [comment]
Not a stupid question at all!  I suspect your experiment will show you it "mostly" works but will require some fixup here and there.  I edited a couple of glyphs (mostly just resize or reposition in box), and also the GPOS rules to align symbols are otpimzied for the specific glyph sizes & positions in Doulos.  But it wouldn't be a whole lot of work to Campania-ize another font.
