### ISSUE TITLE
Word Formatting Issues

### ISSUE THREAD

**Issue by ThomasPosen** [MarcSabatella/Campania#14]
This is an excellent font! I'm having a formatting issue in word, however. I'm using the OTF version on Mac OSX Catalina. The figured bass numbers are offset in word (see the attached). I've enabled "Use contextual alternates." Do you know of any way to fix this in word? 

<img width="172" alt="Screen Shot 2021-01-13 at 12 11 08" src="https://user-images.githubusercontent.com/62619828/104485383-6c949980-5598-11eb-8f6b-9f099294f07d.png">

**Comment by MarcSabatella** [comment]
Unfortunately I don't have much insight into Word.  But isn't there a different option where you need to explicitly enable OpenType features at all?

Does this problem only occur when using multiple stacks and hyphens like that, or do you see it even with a simple V75?  Also, did you type that as V75-43?  That works fine for me, but I don't have Word to test with.

**Comment by fkretlow** [comment]
I apologise in advance for the possibly insulting question, but just in case: Have you activated the `kern` feature as well?

**Comment by ThomasPosen** [comment]
The kern feature solved it! Thanks @fkretlow. My font knowledge is limited.
