### ISSUE TITLE
Thanks for this font

### ISSUE THREAD

**Issue by DP-Upstate** [MarcSabatella/Campania#3]
Thank you for creating this and making it available.  I was looking for a font to do harmonic analysis.  I found Figurato, which is great for actual figured bass but not for what I need.  So far Campania is doing just what I want; I have tried it in MS Word as well as OpenOffice (Windows 10).

Thanks also for all your work on MuseScore, which I use.

**Comment by MarcSabatella** [comment]
I appreciate the feedback!
