### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by billhails** [MarcSabatella/Campania#4]
First off, thanks for this awesome font, I've started using it in MuseScore and it works a treat.

I've found a tricky corner case though.

I often notate the Neapolitan and augmented  sixth chords as just "Ne", "It", "Ge", and "Fr". For "It" the "t" gets replaced by a triangle, I can work around by using all caps but Is it possible to have special treatment for these common idioms?

**Comment by MarcSabatella** [comment]
Nice catch, yes, that's a problem I should fix.  Really, I think I might just remove "t" as the synonym for triangle completely, and leave it as just "^".

BTW, you might also be able to work around by inserting a zero-width character between the I and t - the substitution rule only cuts in if the t directly follows a letter.

**Comment by MarcSabatella** [comment]
Fixed by removing "t" as synonym for triangle.  "^" is good enough.

**Comment by billhails** [comment]
Perfect, thanks so much!
